### PR TITLE
More Swift-like Naming Conventions

### PR DESCRIPTION
**Pull request by MaddTheSane**
* Use more Swift-like naming conventions
* Add Objective-C properties.
* Mark some enums with CF_ENUM: they're more Swift-friendly.
* Change the scaling of vector files to single scale.

### CODE REVIEW

**Comment by dirkwhoffmann** [comment]
Hi @MaddTheSane,

I’ve just seen your merge request. It’s awesome! In programming, code quality is one of the most important things to me and so I'm glad that you contribute your high expertise in Swift and ObjC programming here. 

I see that your modifications cover 4 areas: 

- Use more Swift-like naming conventions

  Perfect. I’ll adapt all of them.

- Add Objective-C properties.

  Perfect. It makes the code much more readable. The only reason I didn’t use ObjC properties before ist that I didn’t know that they exist. Hence, by reading your changes, I’ve already learned a lot new stuff in minutes. 

- Mark some enums with CF_ENUM: they're more Swift-friendly.

  This one might be tricky. If I understand it correctly, this one requires 

      #include <CoreFoundation/CoreFoundation.h>

  which makes it Mac only. But I need to keep the core emulator generic. I’d like to keep the code in a state that makes it compilable on Windows, Linux, and WASM without modifications. Is there a way to keep portability while using the enums more Swift-friendly at the same time? 

-  Change the scaling of vector files to single scale

   This belongs to the category where the coder (me) didn’t really know what he is doing. By looking at the old .json files, I understand that I (accidentally) voted for using different images for different scaling sizes. Your fix is definitely the right thing to do here. But I’m wondering what the implications of the original code were. Let’s look at this example:
```
  "images" : [	
     {		     
       "idiom" : "universal",		      
       "filename" : "rom_hyperion.pdf",		     
       "scale" : "1x"		
     },		
     {		
       "idiom" : "universal",		
       "scale" : "2x"		
     },		
     {		
       "idiom" : "universal",		
       "scale" : "3x"		
     }		     
   ],
```
  Do you know which file macOS would pick in the „2x“ case? Would it still pick „rom_hyperion.pdf“ from the „1x“ section or would it refuse to display an image? As I said, I’m just curious. It’s undoubtedly correct to remove the case  distinction here, because the same file is supposed to be used in all cases.

**Comment by MaddTheSane** [comment]
`CF_ENUM` can be worked around. `CF_ENUM` is just a bit of preprocessor hackery to make using `__attribute__` look better.

I'll write something that will make Swift and non-Apple platforms happy.

**Comment by MaddTheSane** [comment]
cb352b0 and d461b17 should work around the need for the CoreFoundation include.

**Comment by dirkwhoffmann** [comment]
> cb352b0 and d461b17 should work around the need for the CoreFoundation include.

Awesome!

I've merged in the pull request into the main branch and synced it with the dev branch. I had to resolve some merge conflicts there, but I think everything is up and running again.

😎

**Pull request merged**
